<?php

namespace ContainerTOl4FRY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5KbS17fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5KbS17f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5KbS17f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'via' => ['privates', '.errored..service_locator.5KbS17f.App\\Entity\\Vias', NULL, 'Cannot autowire service ".service_locator.5KbS17f": it needs an instance of "App\\Entity\\Vias" but this type has been excluded in "config/services.yaml".'],
        ], [
            'via' => 'App\\Entity\\Vias',
        ]);
    }
}
