<?php

namespace ContainerTOl4FRY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateAdminCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateAdminCommand' shared autowired service.
     *
     * @return \App\Command\GenerateAdminCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'GenerateAdminCommand.php';

        $container->privates['App\\Command\\GenerateAdminCommand'] = $instance = new \App\Command\GenerateAdminCommand(($container->privates['App\\Repository\\UsuariosRepository'] ?? $container->load('getUsuariosRepositoryService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:create-admin');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
