<?php

namespace ContainerTOl4FRY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantsApiControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.22cmh1O.App\Controller\Admin\Api\RestaurantsApiController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.22cmh1O.App\\Controller\\Admin\\Api\\RestaurantsApiController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'restaurante' => ['privates', '.errored..service_locator.22cmh1O.App\\Entity\\Restaurantes', NULL, 'Cannot autowire service ".service_locator.22cmh1O": it needs an instance of "App\\Entity\\Restaurantes" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'restaurante' => 'App\\Entity\\Restaurantes',
            'entityManager' => '?',
            'fileUploader' => 'App\\Service\\FileUploader',
            'validator' => '?',
        ]))->withContext('App\\Controller\\Admin\\Api\\RestaurantsApiController::update()', $container);
    }
}
