<?php

namespace ContainerTOl4FRY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantsApiControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gyKsi0P.App\Controller\Admin\Api\RestaurantsApiController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gyKsi0P.App\\Controller\\Admin\\Api\\RestaurantsApiController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'restaurante' => ['privates', '.errored..service_locator.gyKsi0P.App\\Entity\\Restaurantes', NULL, 'Cannot autowire service ".service_locator.gyKsi0P": it needs an instance of "App\\Entity\\Restaurantes" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'restaurante' => 'App\\Entity\\Restaurantes',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\Api\\RestaurantsApiController::delete()', $container);
    }
}
