<?php

namespace ContainerTOl4FRY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZonas3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AsXtqhJ.App\Entity\Zonas' shared service.
     *
     * @return \App\Entity\Zonas
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AsXtqhJ": it needs an instance of "App\\Entity\\Zonas" but this type has been excluded in "config/services.yaml".');
    }
}
