<?php

namespace ContainerTOl4FRY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZonesApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\Api\ZonesApiController' shared autowired service.
     *
     * @return \App\Controller\Admin\Api\ZonesApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'ZonesApiController.php';

        $container->services['App\\Controller\\Admin\\Api\\ZonesApiController'] = $instance = new \App\Controller\Admin\Api\ZonesApiController();

        $instance->setContainer(($container->privates['.service_locator.rMO7Ull'] ?? $container->load('get_ServiceLocator_RMO7UllService'))->withContext('App\\Controller\\Admin\\Api\\ZonesApiController', $container));

        return $instance;
    }
}
