<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuarios extends \App\Entity\Usuarios implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'ascensos' => [parent::class, 'ascensos', null],
        "\0".parent::class."\0".'avatar' => [parent::class, 'avatar', null],
        "\0".parent::class."\0".'comentarios' => [parent::class, 'comentarios', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'fechaRegistro' => [parent::class, 'fechaRegistro', null],
        "\0".parent::class."\0".'fotos' => [parent::class, 'fotos', null],
        "\0".parent::class."\0".'genero' => [parent::class, 'genero', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'totalAscensos' => [parent::class, 'totalAscensos', null],
        "\0".parent::class."\0".'verificado' => [parent::class, 'verificado', null],
        'ascensos' => [parent::class, 'ascensos', null],
        'avatar' => [parent::class, 'avatar', null],
        'comentarios' => [parent::class, 'comentarios', null],
        'email' => [parent::class, 'email', null],
        'fechaRegistro' => [parent::class, 'fechaRegistro', null],
        'fotos' => [parent::class, 'fotos', null],
        'genero' => [parent::class, 'genero', null],
        'id' => [parent::class, 'id', null],
        'nombre' => [parent::class, 'nombre', null],
        'password' => [parent::class, 'password', null],
        'roles' => [parent::class, 'roles', null],
        'totalAscensos' => [parent::class, 'totalAscensos', null],
        'verificado' => [parent::class, 'verificado', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
