<?php

namespace ContainerFyUaMtt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3m6KIZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3m6_kIZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3m6_kIZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'zona' => ['privates', '.errored..service_locator.3m6_kIZ.App\\Entity\\Zonas', NULL, 'Cannot autowire service ".service_locator.3m6_kIZ": it needs an instance of "App\\Entity\\Zonas" but this type has been excluded in "config/services.yaml".'],
        ], [
            'zona' => 'App\\Entity\\Zonas',
        ]);
    }
}
