<?php

namespace ContainerFyUaMtt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClimbsApiControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vK33Y_h.App\Controller\Admin\Api\ClimbsApiController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vK33Y_h.App\\Controller\\Admin\\Api\\ClimbsApiController::register()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'via' => ['privates', '.errored..service_locator.vK33Y_h.App\\Entity\\Vias', NULL, 'Cannot autowire service ".service_locator.vK33Y_h": it needs an instance of "App\\Entity\\Vias" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'via' => 'App\\Entity\\Vias',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\Api\\ClimbsApiController::register()', $container);
    }
}
