<?php

namespace ContainerFyUaMtt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantes3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zXwSnHp.App\Entity\Restaurantes' shared service.
     *
     * @return \App\Entity\Restaurantes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zXwSnHp": it needs an instance of "App\\Entity\\Restaurantes" but this type has been excluded in "config/services.yaml".');
    }
}
