<?php

namespace ContainerFyUaMtt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoutesApiControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9S5V48X.App\Controller\Admin\Api\RoutesApiController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9S5V48X.App\\Controller\\Admin\\Api\\RoutesApiController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'via' => ['privates', '.errored..service_locator.9S5V48X.App\\Entity\\Vias', NULL, 'Cannot autowire service ".service_locator.9S5V48X": it needs an instance of "App\\Entity\\Vias" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'via' => 'App\\Entity\\Vias',
            'entityManager' => '?',
            'fileUploader' => 'App\\Service\\FileUploader',
            'validator' => '?',
        ]))->withContext('App\\Controller\\Admin\\Api\\RoutesApiController::update()', $container);
    }
}
