<?php

namespace ContainerFyUaMtt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoutesApiControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ku7O0hu.App\Controller\Admin\Api\RoutesApiController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ku7O0hu.App\\Controller\\Admin\\Api\\RoutesApiController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'via' => ['privates', '.errored..service_locator.Ku7O0hu.App\\Entity\\Vias', NULL, 'Cannot autowire service ".service_locator.Ku7O0hu": it needs an instance of "App\\Entity\\Vias" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
        ], [
            'via' => 'App\\Entity\\Vias',
            'em' => '?',
            'fileUploader' => 'App\\Service\\FileUploader',
        ]))->withContext('App\\Controller\\Admin\\Api\\RoutesApiController::delete()', $container);
    }
}
