<?php

namespace ContainerFyUaMtt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVias2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9S5V48X.App\Entity\Vias' shared service.
     *
     * @return \App\Entity\Vias
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9S5V48X": it needs an instance of "App\\Entity\\Vias" but this type has been excluded in "config/services.yaml".');
    }
}
