<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTOl4FRY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTOl4FRY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTOl4FRY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTOl4FRY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTOl4FRY\App_KernelDevDebugContainer([
    'container.build_hash' => 'TOl4FRY',
    'container.build_id' => '21417761',
    'container.build_time' => 1733674284,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTOl4FRY');
